spring.config.import=vault://secret/MyApp,vault://secret/MyApp/dev

dev.camp.security.environment=dev

logging.level.sql=debug
logging.level.web=debug
logging.level.org.springframework.security=debug

spring.web.error.include-stacktrace=always
spring.web.error.include-message=always
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2c
